-record(analysis_report,
	{
	  exp,
	  loc={{0,0},{0,0}},
	  context=[],
	  type=bool,
	  matched=0,
	  nonmatched=0,
	  matchedsubs=[],
	  nonmatchedsubs=[],
	  msubsproportion=1.0,
	  nmsubsproportion=1.0
	}).
